### ISSUE TITLE
 Error decoding JSON

### ISSUE THREAD

**Issue by Cheomm88** [localidata/CKAN-Resource-Updater-for-Pentaho-Data-Integration#1]
Hola,
he seguido los pasos del tutorial https://www.localidata.com/como-actualizar-recursos-de-ckan-a-traves-de-pentaho-data-integration/ pero en Pentaho me devuelve el siguiente error:

Message: Server returned HTTP response code: 400 for URL: http://localhost/api/action/resource_create

Mientras en el Log del CKAN me encuentro con esto:

ERROR [ckan.controllers.api] Bad request data: Error decoding JSON data. Error: JSONDecodeError('Expecting value: line 1 column 2 (char 1)',) JSON data extracted from the request: '--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="upload"; filename="Untitled7469103390843862851.csv"\\r\\nContent-type: application/octet-stream\\r\\n\\r\\n\\xef\\xbb\\xbfPersonas\\r\\nnull\\r\\n\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="package_id"\\r\\n\\r\\ntest-pentaho\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="name"\\r\\n\\r\\nUntitled\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="format"\\r\\n\\r\\nCSV\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="description"\\r\\n\\r\\ntest-pentaho\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="last_modified"\\r\\n\\r\\n2018-01-09T12:24:42.000404\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;\\r\\nContent-Disposition: form-data; name="url"\\r\\n\\r\\n\\r\\n--fIPq9_-mR-RrHnCyRoMGJ1sklf3Iy8HE7WM;--'

Lo único que he creado en mi Data Grid es una tabla con una columna numérica "Personas" y una fila con el valor "10".

A través de postman he podido crear un nuevo recurso en el dataset, por lo que entiendo que mi API KEY es válida, así como la configuración del CKAN.

**Comment by jcballesteros** [comment]
Buenos días,

acabo de replicar el ejemplo que nos comentas y me ha funcionado bien. He probado con columna de tipo integer y number.

¿Nos puedes pasar tu fichero ktr? 

PD: ¿Que versión de CKAN estas utilizando?

**Comment by Cheomm88** [comment]
Buenos días,
Viendo /api/util/status me sale que tengo instalada la versión 2.1.6.

No me ha dejado subir el ktr, puedes bajarlo de aquí https://drive.google.com/file/d/1SEv1jGbJdNi-8e1jOuxsEVyPZftU_b_9/view?usp=sharing

Saludos!

**Comment by jcballesteros** [comment]
Tu KTR nos funciona.

Hemos visto que no tienes tipado el tipo de la columna "datos", y aún así nos funciona. 

Sólo puede ser la versión de CKAN, estas utilizando una versión muy antigua. Nosotros lo estamos probando en un 2.7.  Debería funcionar en 2.6, 2.5 y 2.4

Intenta probarlo en https://demo.ckan.org/es/ (ahora esta caido)

Si necesitas ayuda con CKAN no dudes en preguntarnos (developer@localidata.com).

**Comment by Cheomm88** [comment]
De acuerdo,
muchas gracias!

**Comment by Cheomm88** [comment]
Con demo.ckan.org si funciona.
