### ISSUE TITLE
Problem with uploading dataset to CKAN

### ISSUE THREAD

**Issue by ddoezeja** [localidata/CKAN-Resource-Updater-for-Pentaho-Data-Integration#2]
I'm trying to upload a dataset to CKAN (demo.ckan.org).
I get a failure:
2018/05/28 12:17:38 - CKAN DataStore Upload.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : java.lang.NullPointerException
2018/05/28 12:17:38 - CKAN DataStore Upload.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : No valid resource ID to upload data to.
Please help!

**Comment by jcballesteros** [comment]
In demo.ckan.org I always have a 403 error, but in another enviroments the plugin works fine.
